exp_name: MAAC-R
result_dir: ../results/MAAC-R
# 第一个cuda device的编号, -1代表cpu
first_device: 0
# cuda device的数量, 使用cpu时无效
gpus: 1
seed: 42
cooperative: 0.3
environment:
  n_uav: 5
  m_targets: 10
  x_max: 2000
  y_max: 2000
  na: 12  # 离散化动作空间维数

uav:
  dt: 1
  v_max: 20
  h_max: 6  # 表示 pi / 6
  dc: 500
  dp: 200
  alpha: 0.6
  beta: 0.2
  gamma: 0.2

target:
  v_max: 5
  h_max: 6  # 表示 pi / 6

actor_critic:
  sample_size: 20000
  actor_lr: 1e-4
  critic_lr: 1e-4
  hidden_dim: 256
  gamma: 0.95

pmi:
  hidden_dim: 128
  b2_size: 3000
  batch_size: 128